### ISSUE TITLE
Multiple games bug

### ISSUE THREAD

**Issue by JohnBakhmat** [DenisAliev/TicTacToeTelegramBot#2]
# Бот не сбрасывает результаты прошлых игр
![Telegram_xKhVxvB1TZ](https://user-images.githubusercontent.com/34962307/126032884-37b210e3-cfc6-49ab-9f66-dfbd8d2c737a.png)

**Comment by DenisAliev** [comment]
The bug was fixed

**Comment by DenisAliev** [comment]
The bug have been fixed
